---
language: python
services: docker
python:
  - "2.7"
  # 3.5 should work once Ansible Container 0.9.2+ is released.
  # See: https://github.com/ansible/ansible-container/issues/533
  # - "3.5"

install:
  # Install requirements.
  - pip install -r ansible-requirements.txt

  # Install ansible-container.
  - git clone https://github.com/ansible/ansible-container.git
  - cd ansible-container
  - pip install -e .[docker]
  - cd ..
  # (Source build required until 0.9.2 is released.)
  # - pip install ansible-container[docker]

script:
  - ansible-container --debug --var-file vars-6.x.yml build
  # - ansible-container --debug --var-file vars-5.x.yml build
  # - ansible-container --debug --var-file vars-4.x.yml build

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
