---
language: python
services: docker

python:
  - "2.7"
  - "3.6"

env:
  - install_method=source
  - install_method=pip

matrix:
  allow_failures:
    - env: install_method=pip

install:
  # Install requirements.
  - pip install -r ansible-requirements.txt

  # Install latest HEAD of ansible-container from source.
  - |
    if [ "${install_method}" == "source" ]; then
      git clone https://github.com/ansible/ansible-container.git
      cd ansible-container
      pip install -e .[docker]
      cd ..
    fi
  # Install latest stable release of ansible-container from pip.
  - |
    if [ "${install_method}" == "pip" ]; then
      # See: https://github.com/ansible/ansible-container/pull/870 (at least
      # until Ansible Container 0.9.3+ is released.
      pip install docker==2.7.0
      pip install ansible-container[docker]
    fi

script:
  - ansible-container --var-file vars-7.x.yml build --no-container-cache
  - ansible-container --var-file vars-6.x.yml build --no-container-cache
  - ansible-container --var-file vars-5.x.yml build --no-container-cache
  - ansible-container --var-file vars-4.x.yml build --no-container-cache
  - ansible-container --var-file vars-3.x.yml build --no-container-cache

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
