---
language: python
services: docker
python:
  - "2.7"
  # 3.5 should work once Ansible Container 0.9.2+ is released.
  # See: https://github.com/ansible/ansible-container/issues/533
  # - "3.5"

install:
  - pip install -r ansible-requirements.txt
  - pip install ansible-container[docker]

script:
  - ansible-container --debug --var-file vars.yml build
