galaxy_info:
  author: Jeff Geerling
  description: Apache Solr container for Docker.
  company: Midwestern Mac, LLC
  license: MIT / BSD

  min_ansible_container_version: 0.9.1

  galaxy_tags:
    - solr
    - docker
    - container
    - apache
    - search
    - lucene
    - engine
    - text
