galaxy_info:
  author: Jeff Geerling
  description: Apache Solr container for Docker.
  company: Midwestern Mac, LLC

  # If the issue tracker for your role is not on GitHub, uncomment the
  # next line and provide a value
  # issue_tracker_url:

  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: license (GPLv2, CC-BY, etc)

  min_ansible_container_version: 0.9.1

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If travis integration is cofigured, only notification for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.
  #github_branch:

  tags:
    - solr
    - docker
    - container
    - apache
    - search
    - lucene
    - engine
    - text
