  - gather_facts: false
    tasks:
      - docker_service:
            definition:
                services: &id001
                    solr:
                        environment:
                          - DEBUG=1
                        image: acsolr-solr:20170630025614
                        command:
                          - /opt/solr/bin/solr
                          - start
                          - -f
                          - -force
                        ports:
                          - 8983:8983
                version: '2'
            state: present
            project_name: acsolr
        tags:
          - start
      - docker_service:
            definition:
                services: *id001
                version: '2'
            state: present
            project_name: acsolr
            restarted: true
        tags:
          - restart
      - docker_service:
            definition:
                services: *id001
                version: '2'
            state: present
            project_name: acsolr
            stopped: true
        tags:
          - stop
      - docker_service:
            definition:
                services: *id001
                version: '2'
            state: absent
            project_name: acsolr
            remove_volumes: yes
        tags:
          - destroy
      - docker_image:
            state: absent
            force: yes
            name: acsolr-solr:20170630025614
        tags: destroy
      - docker_image:
            state: absent
            force: yes
            name: acsolr-solr:latest
        tags: destroy
      - docker_image:
            state: absent
            force: yes
            name: acsolr-conductor:latest
        tags: destroy
    hosts: localhost
